template: true 
valuesFilePath: ./values.yml

resources:
  - name: myThirdRepo
    type: GitRepo # defines the resource type
    configuration: # defines the resource definition
      gitProvider: {{ .Values.myRepo.gitProvider }}
      path: {{ .Values.myRepo.path }}
  - name: propertyBag_runtime_c
    type: PropertyBag
    configuration:
      foo: bar
      foo1: bar1
      foo2: bar2
  - name: step_r_c_1
    type: PropertyBag
    configuration:
      key: value
  - name: step_r_c_2
    type: PropertyBag
    configuration:
      key: value
  - name: step_r_c_3
    type: PropertyBag
    configuration:
      key: value
  - name: step_r_c_4
    type: PropertyBag
    configuration:
      key: value
  - name: step_r_c_5
    type: PropertyBag
    configuration:
      key: value

pipelines:
  - name: pipeline_runtime_custom_adityan
    configuration:
      runtime: 
        type: image
        image: 
          custom:
            name: jfpip.jfrog.io/jfrog/pipelines-tools
            tag: latest
            registry: artifactory
            sourceRepository: dev-releases-docker-local
    steps: #step_r_c definiton
      - name: step_r_c_1
        type: Bash
        configuration:
          affinityGroup: ag1
          inputResources:
            - name: mySecondRepo
        execution:
          onExecute:
            - printenv
            - node -v
      - name: step_r_c_2
        type: Bash
        configuration:
          affinityGroup: ag1
          inputSteps: 
            - name: step_r_c_1
        execution:
          onExecute:
            - echo "Executed step_r_c_1_1"
            - node -v
      - name: step_r_c_3
        type: Bash
        configuration: 
          inputSteps: 
            - name: step_r_c_2
        execution:
          onExecute:
            - echo "Executed step_r_c_1_2"
            - node -v
      - name: step_r_c_4
        type: Bash
        configuration: 
          timeoutSeconds: 1
          priority: 2
          inputSteps: 
            - name: step_r_c_2
        execution:
          onExecute:
            - sleep 3
            - node -v
          onFailure:
            - echo "Timed Out"
      - name: step_r_c_5
        type: Bash
        configuration: 
          priority: 1
          inputSteps: 
            - name: step_r_c_2
        execution:
          onExecute:
            - echo "Executed step_r_c_1_5"
            - node -v
      - name: step_r_c_6
        type: Bash
        configuration: 
          inputSteps: 
            - name: step_r_c_3
            - name: step_r_c_5
            - name: step_r_c_4
        execution:
          onExecute:
            - echo "Executed step_r_c_1_6"
      - name: step_r_c_7
        type: Bash
        configuration: 
          inputResources:
            - name: mySecondRepo
          inputSteps: 
            - name: step_r_c_3
            - name: step_r_c_5
            - name: step_r_c_6
        execution:
          onExecute:
            - echo "Executed step_r_c_1_7"
            - node -v
          onSuccess:
            - echo "Executed Successfully"

      