template: true 
valuesFilePath: ./values.yml

resources:
  - name: myFirstRepo
    type: GitRepo # defines the resource type
    configuration: # defines the resource definition
      gitProvider: {{ .Values.myRepo.gitProvider }}
      path: {{ .Values.myRepo.path }}
  - name: propertyBag
    type: PropertyBag
    configuration:
      foo: bar
      foo1: bar1
      foo2: bar2
  - name: step_r_1
    type: PropertyBag
    configuration:
      key: value
  - name: step_r_2
    type: PropertyBag
    configuration:
      key: value
  - name: step_r_3
    type: PropertyBag
    configuration:
      key: value
  - name: step_r_4
    type: PropertyBag
    configuration:
      key: value
  - name: step_r_5
    type: PropertyBag
    configuration:
      key: value

pipelines:
  - name: pipeline_runtime_auto_adityan
    configuration:
      runtime: 
        type: image
        image: 
          auto:
            language: node
            version: "16"
    steps: #step_r definiton
      - name: step_r_1
        type: Bash
        configuration:
          affinityGroup: ag1
          inputResources:
            - name: myFirstRepo
        execution:
          onExecute:
            - printenv
      - name: step_r_2
        type: Bash
        configuration:
          affinityGroup: ag1
          inputSteps: 
            - name: step_r_1
        execution:
          onExecute:
            - echo "Executed step_r_1_1"
      - name: step_r_3
        type: Bash
        configuration: 
          inputSteps: 
            - name: step_r_2
        execution:
          onExecute:
            - echo "Executed step_r_1_2"
      - name: step_r_4
        type: Bash
        configuration: 
          timeoutSeconds: 1
          priority: 2
          inputSteps: 
            - name: step_r_2
        execution:
          onExecute:
            - sleep 3
          onFailure:
            - echo "Timed Out"
      - name: step_r_5
        type: Bash
        configuration: 
          priority: 1
          inputSteps: 
            - name: step_r_2
        execution:
          onExecute:
            - echo "Executed step_r_1_5"
      - name: step_r_6
        type: Bash
        configuration: 
          inputSteps: 
            - name: step_r_3
            - name: step_r_5
            - name: step_r_4
        execution:
          onExecute:
            - echo "Executed step_r_1_6"
      - name: step_r_7
        type: Bash
        configuration: 
          inputResources:
            - name: myFirstRepo
          inputSteps: 
            - name: step_r_3
            - name: step_r_5
            - name: step_r_6
        execution:
          onExecute:
            - echo "Executed step_r_1_7"
          onSuccess:
            - echo "Executed Successfully"

      