template: true 
valuesFilePath: ./values.yml

resources:
  - name: myHybrid
    type: GitRepo # defines the resource type
    configuration: # defines the resource definition
      gitProvider: {{ .Values.myRepo.gitProvider }}
      path: {{ .Values.myRepo.path }}
  - name: propertyBag_runtime_h
    type: PropertyBag
    configuration:
      foo: bar
      foo1: bar1
      foo2: bar2
  - name: step_r_h_1
    type: PropertyBag
    configuration:
      key: value
  - name: step_r_h_2
    type: PropertyBag
    configuration:
      key: value
  - name: step_r_h_3
    type: PropertyBag
    configuration:
      key: value
  - name: step_r_h_4
    type: PropertyBag
    configuration:
      key: value
  - name: step_r_h_5
    type: PropertyBag
    configuration:
      key: value

pipelines:
  - name: pipeline_runtime_hybrid_adityan
    configuration:
      runtime: 
        type: image
        image: 
          custom:
            name: jfpip.jfrog.io/jfrog/pipelines-tools
            tag: latest
            registry: aditya_ent
            sourceRepository: dev-releases-docker-local
    steps: #step_r_h definiton
      - name: step_r_h_1
        type: Bash
        configuration:
          affinityGroup: ag1
          inputResources:
            - name: mySecondRepo
        execution:
          onExecute:
            - printenv
            - echo "step executed"
      - name: step_r_h_2
        type: Bash
        configuration:
          affinityGroup: ag1
          inputSteps: 
            - name: step_r_h_1
        execution:
          onExecute:
            - echo "Executed step_r_h_1_1"
            - echo "step executed"
      - name: step_r_h_3
        type: Bash
        configuration: 
          inputSteps: 
            - name: step_r_h_2
        execution:
          onExecute:
            - echo "Executed step_r_h_1_2"
            - echo "step executed"
      - name: step_r_h_4
        type: Bash
        configuration: 
          priority: 2
          inputSteps: 
            - name: step_r_h_2
        execution:
          onExecute:
            - sleep 3
            - echo "step executed"
          onFailure:
            - echo "Timed Out"
      - name: step_r_h_5
        type: Bash
        configuration: 
          runtime: 
            type: image
            image: 
              auto: 
                language: node
                version: "14"
                versions:
                          - "14"
          priority: 1
          inputSteps: 
            - name: step_r_h_2
        execution:
          onExecute:
            - echo "Executed step_r_h_1_5"
            - node -v
      - name: step_r_h_6
        type: Bash
        configuration: 
          inputSteps: 
            - name: step_r_h_3
            - name: step_r_h_5
            - name: step_r_h_4
        execution:
          onExecute:
            - echo "Executed step_r_h_1_6"
      - name: step_r_h_7
        type: Bash
        configuration: 
          inputResources:
            - name: mySecondRepo
          inputSteps: 
            - name: step_r_h_3
            - name: step_r_h_5
            - name: step_r_h_6
        execution:
          onExecute:
            - echo "Executed step_r_h_1_7"
            - echo "step executed"
          onSuccess:
            - echo "Executed Successfully"

      
