template: true 
valuesFilePath: ./values.yml

resources:
  - name: myEnvRepo
    type: GitRepo # defines the resource type
    configuration: # defines the resource definition
      gitProvider: {{ .Values.myRepo.gitProvider }}
      path: {{ .Values.myRepo.path }}
  - name: propertyBag_env
    type: PropertyBag
    configuration:
      foo: bar
      foo1: bar1
      foo2: bar2

  
pipelines:
  - name: adityan_env_pipeline
    configuration:
      environmentVariables:
        readOnly:
          env1: pipe_value1
          env2: pipe_value2
          env3: pipe_value3
    steps:
      - name: environment_variable_step1
        type: Bash
        configuration:
          environmentVariables:
            key1: val1
            key2: val2
            key3: val3
        execution:
          onExecute:
            - echo $env1
            - echo $env2
            - echo $env3
            - echo $key1
            - echo $key2
            - echo $key3
